on: issues
name: Create Default Labels
jobs:
  labels:
    name: DefaultLabelsActions
    runs-on: ubuntu-latest
    steps:
      - uses: lannonbr/issue-label-manager-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
