name: Default Labels
on: [issues]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: lannonbr/issue-label-manager-action@1.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
